version: '3.9'

services:
  # nginx:
  #   image: nginx:latest
  #   container_name: ctf_nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app
  #   network_mode: host

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf_ad_service
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ctf_service
      - DB_USER=ctf_user
      - DB_PASSWORD=ctf_password
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ctf_postgres
    environment:
      POSTGRES_DB: ctf_service
      POSTGRES_USER: ctf_user
      POSTGRES_PASSWORD: ctf_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
